root = "."
tmp_dir = "tmp"
[build]
  pre_cmd=["go mod download"] 
  cmd="go build -o ./tmp/main ./cmd/main.go"
  bin="tmp/main"
  include_ext=["go"]
  exclude_dir=["vendor", "tmp"]
  run_after_build="chmod +x ./tmp/main"
[log]
  level="debug"
[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
[misc]
# Delete tmp directory on exit
  clean_on_exit = true
